apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql-pod
spec:
  containers:
  - image: eu.gcr.io/lbg-mea-17/task2-db:{{VERSION}}
    name: mysql-container
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: MYSQL_ROOT_PASSWORD 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    run: mysql
  type: ClusterIP
