apiVersion: v1
kind: Service
metadata:
  labels:
    run: example-pod-2
  name: flask-app
spec:
  ports:
  - port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    run: example-pod-2
  type: ClusterIP
