apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    run: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
    volumeMounts:
    - name: nginx-vol
      mountPath: /etc/nginx 
  volumes:
  - name: nginx-vol
    configMap:
      name: nginx-config

