apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql-pod
spec:
  containers:
  - image: eu.gcr.io/lbg-mea-17/task2-db:v1
    name: mysql-container
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password123
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    run: mysql
  type: ClusterIP
